### ISSUE TITLE
 terasoluna-sample/terasoluna-batch-tutorialのSMP001,004,005がAbstractTransactionBLogicを継承しない方が良いのではないか

### ISSUE THREAD

**Issue by kudoueiji** [terasoluna-batch/terasoluna-sample#1]
SMP001,SMP004,SMP005のBLogicはAbstractTransactionBLogicを継承して実装していますが、BLogicインターフェースをimplementsする実装になっていないのに理由があるのでしょうか。

SMP001,SMP005のBLogicクラスでは、コレクタでdaoを使用しています。
このコレクタはAbstractTransactionBLogicによるトランザクション管理とは
異なるトランザクションで実行されるためBLogicインターフェースをimplementsした方が良いかと思いました。
現状の実装だと、チュートリアルで学習する人が、
コレクタによるDBアクセスもAbstractTransactionBLogicによって
トランザクション管理されていると勘違いする可能性があるように思います。

また、SMP004はDBアクセスはなく、ファイル入出力だけ行っていますが、AbstractTransactionBLogicを継承しています。
こちらも実装者以外の人がソースを見た時に、ＤＢアクセスを伴う業務と勘違いするような実装方法に思えます。

TERASOLUNA Batch Frameworkの機能説明書においても、
「トランザクションをフレームワーク側で管理する場合は抽象クラスであ
るAbstractTransactionBLogic クラスを継承すること。」
といった記述が見られるため、BLogicインターフェースとAbstractTransactionBLogic抽象クラスは使い分けることを前提としているようにも見えるため、
BLogicインターフェースをimplementsする実装とした方が良いかと思います。

**Comment by kuramotoki** [comment]
コメントありがとうございます。
ver3.6.0の以下のコミットで修正しました。
424715aada8491f280e3e38e714359c0e67db113

本Issueはクローズします。
