### ISSUE TITLE
BLogic中の異常終了時に返す終了コードは、-1ではなく255を返した方がいいのではないでしょうか

### ISSUE THREAD

**Issue by kudoueiji** [terasoluna-batch/terasoluna-sample#2]
terasoluna-sample/terasoluna-batch-tutorial/src/main/java/jp/terasoluna/batch/tutorial/
配下のsample001～sample005のBLogicにおいて、異常終了時に終了コード-1を返していますが、
255を返したほうがいいのではないでしょうか。

Linux環境でbashなどを用いた場合、スケジューラへ返却できる終了コードは0～255の範囲となります。
BLogic内で-1を返した場合、255に変換されますが、初めから255を返した方がいいように思います。
また、Terasoluna Batch Frameworkで提供されているDefaultExceptionHandlerでも255を返すような実装となっています。
※DefaultExceptionHandlerの設定されたジョブのBLogicクラスで-1を返しているため、同義のステータスコードを-1や255の複数表現を用いた実装になっているため違和感を感じます。

**Comment by kuramotoki** [comment]
コメントありがとうございます。
ver3.6.0の以下のコミットで修正しました。
78092f89f1eab7206e8adf7f5c311960c91ec52b

本issueはクローズします。
